# Generated by Django 3.0.7 on 2020-11-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='content3',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido 3'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='content1',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido 1'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='content2',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido 2'),
        ),
    ]
